"""betterdb-ai: one install and one import root for the BetterDB AI stack.

Re-exports the five packages that make up the Python SDK — agent cache,
semantic cache, retrieval, agent memory, and the shared Valkey Search
helpers — without adding behaviour of its own.

Names that only one package declares are available straight from the root::

    from betterdb_ai import AgentCache, SemanticCache, MemoryStore, Retriever

Names that more than one package declares as a *different* object are not
flattened, because picking one would silently break ``except`` and
``isinstance`` for the other. Reach those through the child namespace::

    from betterdb_ai import agent_cache, semantic_cache

    try:
        await cache.llm.check(...)
    except agent_cache.ValkeyCommandError:
        ...

``AMBIGUOUS`` lists those names and ``NAMESPACES`` the five child modules.
"""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _distribution_version

import betterdb_agent_cache as agent_cache
import betterdb_agent_memory as memory
import betterdb_retrieval as retrieval
import betterdb_semantic_cache as semantic_cache
import betterdb_valkey_search_kit as search_kit
from betterdb_agent_cache import (
    DEFAULT_COST_TABLE,
    AgentCache,
    AgentCacheError,
    AgentCacheOptions,
    AgentCacheStats,
    AgentCacheUsageError,
    BlockHints,
    LlmCacheMessage,
    LlmCacheParams,
    LlmCacheResult,
    LlmStoreOptions,
    SessionStats,
    TierDefaults,
    TierStats,
    ToolCacheResult,
    ToolDefinition,
    ToolEffectivenessEntry,
    ToolPolicy,
    ToolStats,
    ToolStoreOptions,
)
from betterdb_agent_memory import (
    DEFAULT_METRICS_PREFIX,
    DEFAULT_TRACER_NAME,
    MATCH_ALL_MEMORY_QUERY,
    MEMORY_CACHE_TYPE,
    MEMORY_CAPABILITIES,
    AddOp,
    AgentMemory,
    AgentMemoryConfig,
    AgentMemoryOptions,
    AgentMemoryRecallConfig,
    ConsolidateFactsResult,
    ConsolidateResult,
    ConsolidationConfig,
    DeleteOp,
    Fact,
    FactExtractor,
    FactOp,
    MemoryConfigRefreshConfig,
    MemoryConfigSnapshot,
    MemoryDiscovery,
    MemoryDiscoveryConfig,
    MemoryHit,
    MemoryItem,
    MemoryListOptions,
    MemoryListResult,
    MemoryMetrics,
    MemoryScope,
    MemoryStats,
    MemoryStore,
    MemoryStoreClient,
    MemoryTelemetry,
    MemoryTelemetryOptions,
    NoopOp,
    RecallWeights,
    SummarizeFn,
    UnmatchedTombstoneOp,
    UpdateOp,
    apply_ops,
    composite_score,
    create_memory_telemetry,
    recency_decay,
    reconcile,
    similarity_from_distance,
    subject_key,
)
from betterdb_retrieval import (
    REGISTRY_KEY,
    RETRIEVAL_CACHE_TYPE,
    SCORE_FIELD,
    TEXT_FIELD,
    FieldSpec,
    FtCapabilities,
    IndexDescription,
    IndexHealthSnapshot,
    PrometheusRetrievalMetrics,
    QueryFilter,
    QueryHit,
    RecallEstimator,
    RerankFn,
    RetrievalMarker,
    RetrievalMetrics,
    RetrievalOperation,
    RetrievalSchema,
    RetrievalSpan,
    RetrievalTracer,
    Retriever,
    RetrieverClient,
    UpsertEntry,
    VectorAlgorithm,
    VectorMetric,
    VectorSpec,
    build_ft_create_args,
    build_ft_search_query,
    build_retrieval_marker,
    create_analytics,
    create_prometheus_metrics,
    index_name,
    key_prefix,
    parse_percent_indexed,
    resolve_vector_field_name,
)
from betterdb_semantic_cache import (
    CacheCheckOptions,
    CacheCheckResult,
    CacheConfidence,
    CacheStats,
    CacheStoreOptions,
    EmbeddingCacheOptions,
    EmbeddingError,
    IndexInfo,
    InvalidateResult,
    JudgeOptions,
    NearestMiss,
    RerankOptions,
    SemanticCache,
    SemanticCacheOptions,
    SemanticCacheUsageError,
    TelemetryOptions,
    ThresholdEffectivenessResult,
    create_keyword_overlap_rerank,
    extract_binary_refs,
    extract_text,
    sha256,
)
from betterdb_valkey_search_kit import (
    FtIndexStats,
    FtSearchHit,
    decode_float32,
    encode_float32,
    escape_tag,
    is_index_not_found_error,
    parse_dimension_from_info,
    parse_ft_info_stats,
    parse_ft_search_response,
)

#: Read from the installed distribution rather than written here, so it
#: cannot drift from pyproject.toml, which the release workflow rewrites at
#: publish time.
try:
    __version__ = _distribution_version("betterdb-ai")
except PackageNotFoundError:
    __version__ = "0.0.0"

#: The child packages, reachable as ``betterdb_ai.<name>``. Every name a child
#: declares stays reachable here even when it is too ambiguous to flatten.
NAMESPACES = (
    "agent_cache",
    "semantic_cache",
    "retrieval",
    "memory",
    "search_kit",
)

#: Names declared as a different object by more than one child. Deliberately
#: absent from the root; use the namespace of the package you mean.
AMBIGUOUS = (
    "Analytics",
    "BinaryBlock",
    "BinaryNormalizer",
    "BinaryRef",
    "ConfigRefreshOptions",
    "ContentBlock",
    "DiscoveryOptions",
    "EmbedFn",
    "ModelCost",
    "NormalizerConfig",
    "ReasoningBlock",
    "TextBlock",
    "ToolCallBlock",
    "ToolResultBlock",
    "ValkeyCommandError",
    "compose_normalizer",
    "default_normalizer",
    "fetch_and_hash",
    "hash_base64",
    "hash_bytes",
    "hash_url",
    "passthrough",
)

__all__ = [
    "AMBIGUOUS",
    "DEFAULT_COST_TABLE",
    "DEFAULT_METRICS_PREFIX",
    "DEFAULT_TRACER_NAME",
    "MATCH_ALL_MEMORY_QUERY",
    "MEMORY_CACHE_TYPE",
    "MEMORY_CAPABILITIES",
    "NAMESPACES",
    "REGISTRY_KEY",
    "RETRIEVAL_CACHE_TYPE",
    "SCORE_FIELD",
    "TEXT_FIELD",
    "AddOp",
    "AgentCache",
    "AgentCacheError",
    "AgentCacheOptions",
    "AgentCacheStats",
    "AgentCacheUsageError",
    "AgentMemory",
    "AgentMemoryConfig",
    "AgentMemoryOptions",
    "AgentMemoryRecallConfig",
    "BlockHints",
    "CacheCheckOptions",
    "CacheCheckResult",
    "CacheConfidence",
    "CacheStats",
    "CacheStoreOptions",
    "ConsolidateFactsResult",
    "ConsolidateResult",
    "ConsolidationConfig",
    "DeleteOp",
    "EmbeddingCacheOptions",
    "EmbeddingError",
    "Fact",
    "FactExtractor",
    "FactOp",
    "FieldSpec",
    "FtCapabilities",
    "FtIndexStats",
    "FtSearchHit",
    "IndexDescription",
    "IndexHealthSnapshot",
    "IndexInfo",
    "InvalidateResult",
    "JudgeOptions",
    "LlmCacheMessage",
    "LlmCacheParams",
    "LlmCacheResult",
    "LlmStoreOptions",
    "MemoryConfigRefreshConfig",
    "MemoryConfigSnapshot",
    "MemoryDiscovery",
    "MemoryDiscoveryConfig",
    "MemoryHit",
    "MemoryItem",
    "MemoryListOptions",
    "MemoryListResult",
    "MemoryMetrics",
    "MemoryScope",
    "MemoryStats",
    "MemoryStore",
    "MemoryStoreClient",
    "MemoryTelemetry",
    "MemoryTelemetryOptions",
    "NearestMiss",
    "NoopOp",
    "PrometheusRetrievalMetrics",
    "QueryFilter",
    "QueryHit",
    "RecallEstimator",
    "RecallWeights",
    "RerankFn",
    "RerankOptions",
    "RetrievalMarker",
    "RetrievalMetrics",
    "RetrievalOperation",
    "RetrievalSchema",
    "RetrievalSpan",
    "RetrievalTracer",
    "Retriever",
    "RetrieverClient",
    "SemanticCache",
    "SemanticCacheOptions",
    "SemanticCacheUsageError",
    "SessionStats",
    "SummarizeFn",
    "TelemetryOptions",
    "ThresholdEffectivenessResult",
    "TierDefaults",
    "TierStats",
    "ToolCacheResult",
    "ToolDefinition",
    "ToolEffectivenessEntry",
    "ToolPolicy",
    "ToolStats",
    "ToolStoreOptions",
    "UnmatchedTombstoneOp",
    "UpdateOp",
    "UpsertEntry",
    "VectorAlgorithm",
    "VectorMetric",
    "VectorSpec",
    "__version__",
    "agent_cache",
    "apply_ops",
    "build_ft_create_args",
    "build_ft_search_query",
    "build_retrieval_marker",
    "composite_score",
    "create_analytics",
    "create_keyword_overlap_rerank",
    "create_memory_telemetry",
    "create_prometheus_metrics",
    "decode_float32",
    "encode_float32",
    "escape_tag",
    "extract_binary_refs",
    "extract_text",
    "index_name",
    "is_index_not_found_error",
    "key_prefix",
    "memory",
    "parse_dimension_from_info",
    "parse_ft_info_stats",
    "parse_ft_search_response",
    "parse_percent_indexed",
    "recency_decay",
    "reconcile",
    "resolve_vector_field_name",
    "retrieval",
    "search_kit",
    "semantic_cache",
    "sha256",
    "similarity_from_distance",
    "subject_key",
]
