{{- if include "betterdb-monitor.createSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "betterdb-monitor.secretName" . }}
  labels:
    {{- include "betterdb-monitor.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and .Values.db.password (not .Values.db.existingSecret) }}
  db-password: {{ .Values.db.password | quote }}
  {{- end }}
  {{- if and .Values.storage.url (not .Values.storage.existingSecret) }}
  storage-url: {{ .Values.storage.url | quote }}
  {{- end }}
  {{- if and .Values.license.key (not .Values.license.existingSecret) }}
  license-key: {{ .Values.license.key | quote }}
  {{- end }}
{{- end }}
